linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
    - gocritic
    - goimports
    - revive
    - misspell
    - unparam
    - unconvert
    - prealloc
    - noctx
    
  disable:
    - unused
    - gosec
    - dupl

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/eternnoir/gollmscribe
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
  revive:
    confidence: 0.8

issues:
  exclude-use-default: false
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - gocritic
    - path: pkg/providers/
      linters:
        - dupl
    - linters:
        - revive
      text: "don't use an underscore in package name"

run:
  timeout: 5m
  tests: false